# Generated by Django 4.2.16 on 2026-08-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_madrasa_alter_userprofile_role_and_more'),
        ('staff', '0002_staff_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='halaqaassignment',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halaqa_assignments', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='staff',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_attendance', to='users.madrasa'),
        ),
    ]
