# Generated by Django 4.2.16 on 2026-08-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='authorized_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authorized_gate_passes', to='staff.staff'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gate_passes', to='students.student'),
        ),
        migrations.AddConstraint(
            model_name='hostelroom',
            constraint=models.UniqueConstraint(fields=('wing', 'room_number'), name='unique_room_per_wing'),
        ),
        migrations.AddConstraint(
            model_name='hostelallocation',
            constraint=models.UniqueConstraint(fields=('room', 'bed_number'), name='unique_bed_per_room'),
        ),
    ]
