# Generated by Django 4.2.16 on 2026-08-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_madrasa_alter_userprofile_role_and_more'),
        ('hostel', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gate_passes', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='hostelallocation',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_allocations', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='hostelroom',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_rooms', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='hostelwing',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hostel_wings', to='users.madrasa'),
        ),
    ]
