# Generated by Django 4.2.16 on 2026-08-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_madrasa_alter_userprofile_role_and_more'),
        ('finance', '0004_remove_transport_add_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='donor',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donors', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='expense',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='fund',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='studentfeelog',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_logs', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_payments', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='studentmonthlyfee',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_monthly_fees', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='studentsponsorship',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_sponsorships', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='teachersalary',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_salaries', to='users.madrasa'),
        ),
    ]
