# Generated by Django 4.2.16 on 2026-08-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_madrasa_alter_userprofile_role_and_more'),
        ('academics', '0002_subject_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='users.madrasa'),
        ),
    ]
