# Generated by Django 4.2.16 on 2026-08-22 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['department__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Halaqa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('ustad_name', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=200)),
                ('cnic', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'طالب'), ('female', 'طالبہ')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('residential_status', models.CharField(choices=[('day_scholar', 'روزانہ آنے والا'), ('resident', 'ہاسٹل میں مقیم')], default='day_scholar', max_length=20)),
                ('is_mustahiq', models.BooleanField(default=False)),
                ('admission_date', models.DateField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('on_leave', 'رخصت'), ('inactive', 'غیر فعال')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.academicclass')),
                ('current_halaqa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.halaqa')),
            ],
            options={
                'ordering': ['-admission_date', 'full_name'],
            },
        ),
        migrations.AddField(
            model_name='academicclass',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='students.department'),
        ),
        migrations.AddConstraint(
            model_name='academicclass',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='unique_class_per_department'),
        ),
    ]
