# Generated by Django 4.2.16 on 2026-08-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_madrasa_alter_userprofile_role_and_more'),
        ('students', '0004_studentattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicclass',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_classes', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='department',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='halaqa',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='halaqas', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='student',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='users.madrasa'),
        ),
    ]
