# Generated by Django 4.2.16 on 2026-08-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HifzDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sabaq_portion', models.CharField(blank=True, max_length=255)),
                ('sabaqi_portion', models.CharField(blank=True, max_length=255)),
                ('manzil_portion', models.CharField(blank=True, max_length=255)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hifz_logs', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
