# Generated by Django 4.2.16 on 2026-08-22 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hifz', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hifzdailylog',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_hifz_logs', to='staff.staff'),
        ),
        migrations.AddConstraint(
            model_name='hifzdailylog',
            constraint=models.UniqueConstraint(fields=('student', 'date'), name='unique_hifz_log_per_student_day'),
        ),
    ]
