# Generated by Django 4.2.16 on 2026-08-22 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('academic_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_exams', to='students.academicclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='internal_exams', to='academics.subject')),
            ],
            options={
                'ordering': ['-exam_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WafaqBoardRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wafaq_name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wafaq_registrations', to='students.student')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WafaqResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passing_year', models.PositiveSmallIntegerField()),
                ('result', models.CharField(max_length=100)),
                ('registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='exams.wafaqboardregistration')),
            ],
        ),
        migrations.CreateModel(
            name='InternalExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='exams.internalexam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_exam_results', to='students.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='internalexamresult',
            constraint=models.UniqueConstraint(fields=('exam', 'student'), name='unique_internal_result_per_student'),
        ),
    ]
