# Generated by Django 4.2.16 on 2026-08-27 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_madrasa_alter_userprofile_role_and_more'),
        ('exams', '0007_internalexampaper_paper_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalexam',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_exams', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='internalexampaper',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_papers', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='internalexamresult',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='wafaqboardregistration',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wafaq_registrations', to='users.madrasa'),
        ),
        migrations.AddField(
            model_name='wafaqresult',
            name='madrasa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wafaq_results', to='users.madrasa'),
        ),
    ]
